Ext.define('MYOCD.Global', {});

//Global Url variables
var HOME_URL = 'http://www.myownframework.com/',
	CONTACT_API_URL = HOME_URL + 'contacts.json',
	USER_API_URL = HOME_URL + 'users.json',
	USER_BASE_URL = HOME_URL + 'users/',
	USER_REGISTRATION_URL = USER_BASE_URL + 'registration.json',
	USER_LOGIN_URL = USER_BASE_URL + 'sign_in',
	USER_SIGN_OUT_URL = USER_BASE_URL + 'sign_out',
	WORKSPACE_API_URL = HOME_URL + 'workspaces.json',
	DOMAIN_API_URL = HOME_URL + 'domains.json',
	DOMAIN_BASE_URL = HOME_URL + 'domains/',
	COMPANIES_API_URL = HOME_URL + 'companies.json',
	COMPANIES_BASE_URL = HOME_URL + 'companies/',
	PERMISSION_LIBS_BASE_URL = HOME_URL + 'permissionlibs/',
	PERMISSION_CATEGORY_BASE_URL = HOME_URL + 'permissioncategories/',
	PERMISSION_BASE_URL = HOME_URL + 'permissions/',
	ROLE_LIBS_BASE_URL = HOME_URL + 'rolelibs/',
	ROLE_CATEGORY_BASE_URL = HOME_URL + 'rolecategories/',
	ROLE_BASE_URL = HOME_URL + 'roles/',
	COMPANY_TEMPLATE_LIB_BASE_URL = HOME_URL + 'companytemplatelibs/',
	COMPANY_TEMPLATE_CATEGORY_BASE_URL = HOME_URL + 'companytemplatecategories/',
	COMPANY_TEMPLATE_BASE_URL = HOME_URL + 'companytemplates/',
	CLASSIFICATION_LIB_BASE_URL = HOME_URL + 'classificationlibs/', 
	CLASSIFICATION_CATEGORY_BASE_URL = HOME_URL + 'classificationcategories/',
	CLASSIFICATION_BASE_URL = HOME_URL + 'classifications/',
	PRODUCT_CATALOG_LIB_BASE_URL = HOME_URL + 'productlibs/',
	PRODUCT_CATALOG_CATEGORY_BASE_URL = HOME_URL + 'productcategories/',
	PRODUCT_BASE_URL = HOME_URL + 'products/',
	JOB_CATALOG_LIB_BASE_URL = HOME_URL + 'joblibs/',
	JOB_CATALOG_CATEGORY_BASE_URL = HOME_URL + 'jobcategories/',
	JOB_BASE_URL = HOME_URL + 'jobs/',
	COMMUNITY_TEMPLATE_LIB_BASE_URL = HOME_URL + 'communitygrouptemplatelibs/',
	COMMUNITY_TEMPLATE_CATEGORY_BASE_URL = HOME_URL + 'communitygrouptemplatecategories/'
	COMMUNITY_TEMPLATE_BASE_URL = HOME_URL + 'communitygrptemplates/',
	OBJECT_TYPE_LIB_BASE_URL = HOME_URL + 'objecttypelibs/',
	OBJECT_TYPE_CATEGORY_BASE_URL = HOME_URL + 'objecttypecategories/',
	OBJECT_TYPE_BASE_URL = HOME_URL + 'objecttypes/',
	ATTRIBUTE_BASE_URL = HOME_URL + 'attributes/',
	COMPANY_WORKSPACE_BASE_URL = HOME_URL + 'companyws/',
	PERSONAL_WORKSPACE_BASE_URL = HOME_URL + 'personalws/',
	PROJECT_TEMPLATE_LIB_BASE_URL = HOME_URL + 'projecttemplatelibs/',
	PROJECT_TEMPLATE_CATEGORY_BASE_URL = HOME_URL + 'projecttemplatecategories/',
	PROJECT_TEMPLATE_BASE_URL = HOME_URL + 'projecttemplates/',
	FEATURE_TEMPLATE_LIB_BASE_URL = HOME_URL + 'featuretemplatelibs/',
	FEATURE_TEMPLATE_CATEGORY_BASE_URL = HOME_URL + 'featuretemplatecategories/',
	FEATURE_TEMPLATE_BASE_URL = HOME_URL + 'featuretemplates/',
	PRODUCT_ITEMS_BASE_URL = HOME_URL + 'productitems/',
	///// Projects APIs
	PROJECT_API_URL = HOME_URL + 'projects.json',
	PROJECT_BASE_URL = HOME_URL + 'projects/',
	FEATURE_BASE_URL = HOME_URL + 'features/',
	
	VIEW_LIB_BASE_URL = HOME_URL + 'viewlibs/',
	VIEW_CATEGORY_BASE_URL = HOME_URL + 'viewcategories/',
	VIEW_API_URL = HOME_URL + 'views.json',
	VIEW_BASE_URL = HOME_URL + 'views/',
	
	// for companies, communitygroups, personalprofiles, employeeprofiles, memberprofiles.
	EMPLOYEE_PROFILES_BASE_URL = HOME_URL + 'employeeprofiles/',
	COMPANY_PROFILES_BASE_URL = HOME_URL + 'companyprofiles/',
	COMMUNITY_PROFILES_BASE_URL = HOME_URL + 'communitygroupprofiles/',
	PERSONAL_PROFILES_BASE_URL = HOME_URL + 'personalprofiles/',
	
	ATTRIBUTE_BASE_URL = HOME_URL + 'attributes/',
	
	// FEATURE_PRODUCT_FIELDS = ["Id", "Name", "Description", "Created", "Expired", "Type", "Price", "Quantity", "Parent Types"], 
	FEATURE_PRODUCT_FIELDS = ["Id", "Type", "Price", "Quantity", "Parent Types"], 
	
	MODULES_URL = HOME_URL + 'guimodules.json',
    MODULES_BASE_URL = HOME_URL + 'guimodules/',

    ASSOCIATED_TYPE_URL = HOME_URL + '/associatedtypekeys.json',
	
	END = null;

var API_BASE_URL = "http://neo4j.myownframework.com:3000/",
    API_LOGIN_URL = API_BASE_URL + '/users/sign_in.json',
    API_SIGNUP_URL = API_BASE_URL + '/users.json',
    API_COMPANIES_URL = API_BASE_URL + '/companies.json',
    API_COMPANIES_BASE_URL = API_BASE_URL + '/companies/',
    API_INVITATIONS_URL = API_BASE_URL + '/invitations.json',
    API_INVITATIONS_BASE_URL = API_BASE_URL + '/invitations/',
    API_PROJECTS_URL = API_BASE_URL + '/projects.json',
    API_PROJECTS_BASE_URL = API_BASE_URL + '/projects/',
    API_WORKSPACES_URL = API_BASE_URL + '/workspaces.json',
    API_WORKSPACES_BASE_URL = API_BASE_URL + '/workspaces/',
    API_OBJECTTYPESLIBS_URL = API_BASE_URL + '/objecttypeslibs.json',
    API_OBJECTTYPESLIBS_BASE_URL = API_BASE_URL + '/objecttypeslibs/',
    API_OBJECTTYPESLIBS_IMPORT_URL = API_OBJECTTYPESLIBS_BASE_URL + 'import.json',
    API_OBJECTTYPESLIBS_EXCLUDE_URL = API_OBJECTTYPESLIBS_BASE_URL + 'exclude.json',
    API_TEMPLATESLIBS_URL = API_BASE_URL + '/projecttemplateslibraries.json',
    API_TEMPLATESLIBS_BASE_URL = API_BASE_URL + '/projecttemplateslibraries/',
    API_TEMPLATESLIBS_PRIVATE_URL = API_TEMPLATESLIBS_BASE_URL + '/filter/private.json',
    API_TEMPLATESLIBS_PUBLIC_URL = API_TEMPLATESLIBS_BASE_URL + '/filter/public.json',
    API_TEMPLATESLIBS_IMPORT_URL =  API_TEMPLATESLIBS_BASE_URL + 'import.json',
    API_TEMPLATESLIBS_EXCLUDE_URL =  API_TEMPLATESLIBS_BASE_URL + 'exclude.json',
    API_TEMPLATES_BASE_URL = API_BASE_URL + 'projecttemplates/',
    API_COMMUNITIES_URL = API_BASE_URL + '/communitygroups.json',
    API_COMMUNITIES_BASE_URL = API_BASE_URL + '/communitygroups/',
    API_PROJECT_TEMPLATES_LIBS_URL = API_BASE_URL + '/projecttemplateslibraries.json', //not use much, remember ...
    API_CATALOGS_URL = API_BASE_URL + '/catalogs.json',
    API_CATALOGS_BASE_URL = API_BASE_URL + '/catalogs/',
    API_CATALOGS_IMPORT_URL = API_CATALOGS_BASE_URL + '/import.json',
    API_CATALOGS_EXCLUDE_URL = API_CATALOGS_BASE_URL + '/exclude.json',
    API_CATALOGS_PRIVATE_URL = API_CATALOGS_BASE_URL+ '/filter/private.json',
    API_CATALOGS_PUBLIC_URL = API_CATALOGS_BASE_URL+ '/filter/public.json',
    API_FEATURES_BASE_URL = API_BASE_URL + '/features/',
    API_CLASSIFICATIONS_URL = API_BASE_URL + '/classifications.json',
    API_CLASSIFICATIONS_BASE_URL = API_BASE_URL + '/classifications/',
    API_UNIT_OF_MEASURES_URL = API_BASE_URL + '/unit_of_measures.json',
    API_SEARCH_COMPANIES_BASE_URL = API_COMPANIES_BASE_URL + '/search/',
    API_SEARCH_COMMUNITIES_BASE_URL = API_COMMUNITIES_BASE_URL + '/search/',
    API_PRODUCT_ITEMS_BASE_URL = API_BASE_URL + '/productitems/',
    API_OBJECTTYPES_BASE_URL = API_BASE_URL + '/objecttypes/',
    API_OBJECTTYPES_COPY_URL = API_OBJECTTYPES_BASE_URL + '/copy.json',
    API_VALUETYPES_URL = API_BASE_URL + '/valuetypes.json',
    API_TREESNAPSHOT_URL = API_BASE_URL + '/tree_snapshot_tags.json',
    API_TREESNAPSHOTTAG_URL = API_BASE_URL + '/tree_snapshot_tags/node.json',
    API_USER_URL = API_BASE_URL + '/user.json',
    API_PRODUCTS_URL = API_BASE_URL + '/products.json',
    API_PRODUCTS_BASE_URL = API_BASE_URL + '/products/',
    API_ADD_CATEGORY_PRODUCT_URL = API_BASE_URL + '/categories/add_product.json';
    
var MOST_RECENT_VER_TIMESTAMP = 9999999999999;    

var gCurrentWorkspaceId, gCurrentWorkspaceName, gCurrentWorkspaceType, gCurrentWorkspaceCompany;

